### ISSUE TITLE
Packaging dashboard

### ISSUE THREAD

**Issue by hexchain** [netdata/dashboard#83]
I'm trying to package the new netdata dashboard, but it seems that the build process does not produce a `dashboard_info.js`. Is this expected? Where should I obtain this file from?

**Comment by Ferroin** [comment]
It is expected, albeit a bit confusing. There are a couple of files shared between the old and new dashboards, and they're currently kept in their original locations in the main Netdata repo. `dashboard_info.js` is one of them, but I believe there are a few CSS files we're using too.

@jacekkolasa can you confirm this when you get a chance?

**Comment by jacekkolasa** [comment]
hey @hexchain indeed, `dashboard_info.js` was not added to the bundle, because it belongs to the specific Agent, and is independent from Dashboard. In the future it won't be .js, but a DSL file.

This file shouldn't be in the bundle, but should be fetched from Agent via it's server, just like you hit any /api/v1/ endpoints. The same goes for `dashboard.slate.css`, `dashboard.css` and `main.css` files.

Does that answer your question?

I agree it's a little bit confusing, in the future we'll clean the situation and remove more front-end assets from netdata repo

**Comment by hexchain** [comment]
Hi @Ferroin and @jacekkolasa, thanks for the explanation!

> This file shouldn't be in the bundle, but should be fetched from Agent via it's server, just like you hit any /api/v1/ endpoints. The same goes for `dashboard.slate.css`, `dashboard.css` and `main.css` files.

Does that mean `dashboard_info.js` and any related file you mentioned should be provided by the agent, instead of being some static files in the dashboard directory?

**Comment by jacekkolasa** [comment]
@hexchain yes, exactly

**Comment by hexchain** [comment]
Has the situation changed? It seems that those files are still static ones.

**Comment by gpanders** [comment]
I maintain the MacPorts package for netdata and the netdata dashboard and I also got tripped up on this. We're currently having to do a bit of a hack when we install netdata to find all of the files installed by `netdata/dashboard` and remove those from `netdata/netdata` to prevent conflicts when the packages are installed.

Would you guys mind keeping us in the loop when/if this situation changes so package maintainers can update accordingly?
